AppID = ''
Server = ["blocksyncer"]
GrpcAddress = ''

[SpDB]
User = 'root'
Passwd = '1q2w3e4r*'
Address = 'localhost:3306'
Database = 'block_syncer'
ConnMaxLifetime = 0
ConnMaxIdleTime = 0
MaxIdleConns = 0
MaxOpenConns = 0

[PieceStore]
Shards = 0

[PieceStore.Store]
Storage = ''
BucketURL = ''
MaxRetries = 0
MinRetryDelay = 0
TLSInsecureSkipVerify = false
IAMType = ''

[Chain]
ChainID = 'greenfield_9000-1741'
ChainAddress = ["http://localhost:26750"]
GasLimit = 0

[SpAccount]
SpOperateAddress = ''
OperatorPrivateKey = ''
FundingPrivateKey = ''
SealPrivateKey = ''
ApprovalPrivateKey = ''
GcPrivateKey = ''

[Endpoint]
ApproverEndpoint = ''
ManagerEndpoint = ''
DownloaderEndpoint = ''
ReceiverEndpoint = ''
MetadataEndpoint = ''
RetrieverEndpoint = ''
UploaderEndpoint = ''
P2PEndpoint = ''
SignerEndpoint = ''
AuthorizerEndpoint = ''

[Approval]
BucketApprovalTimeoutHeight = 0
ObjectApprovalTimeoutHeight = 0
ReplicatePieceTimeoutHeight = 0

[Bucket]
AccountBucketNumber = 0
FreeQuotaPerBucket = 0
MaxListReadQuotaNumber = 0

[Gateway]
Domain = ''
HttpAddress = ''

[Executor]
MaxExecuteNumber = 0
AskTaskInterval = 0
AskReplicateApprovalTimeout = 0
AskReplicateApprovalExFactor = 0.0
ListenSealTimeoutHeight = 0
ListenSealRetryTimeout = 0
MaxListenSealRetry = 0

[P2P]
P2PPrivateKey = ''
P2PAddress = ''
P2PBootstrap = []
P2PPingPeriod = 0

[Parallel]
GlobalCreateBucketApprovalParallel = 0
GlobalCreateObjectApprovalParallel = 0
GlobalMaxUploadingParallel = 0
GlobalUploadObjectParallel = 0
GlobalReplicatePieceParallel = 0
GlobalSealObjectParallel = 0
GlobalReceiveObjectParallel = 0
GlobalGCObjectParallel = 0
GlobalGCZombieParallel = 0
GlobalGCMetaParallel = 0
GlobalDownloadObjectTaskCacheSize = 0
GlobalChallengePieceTaskCacheSize = 0
GlobalBatchGcObjectTimeInterval = 0
GlobalGcObjectBlockInterval = 0
GlobalGcObjectSafeBlockDistance = 0
GlobalSyncConsensusInfoInterval = 0
UploadObjectParallelPerNode = 0
ReceivePieceParallelPerNode = 0
DownloadObjectParallelPerNode = 0
ChallengePieceParallelPerNode = 0
AskReplicateApprovalParallelPerNode = 0
QuerySPParallelPerNode = 0

[Task]
UploadTaskSpeed = 0
DownloadTaskSpeed = 0
ReplicateTaskSpeed = 0
ReceiveTaskSpeed = 0
SealObjectTaskTimeout = 0
GcObjectTaskTimeout = 0
GcZombieTaskTimeout = 0
GcMetaTaskTimeout = 0
SealObjectTaskRetry = 0
ReplicateTaskRetry = 0
ReceiveConfirmTaskRetry = 0
GcObjectTaskRetry = 0
GcZombieTaskRetry = 0
GcMetaTaskRetry = 0

[Monitor]
DisableMetrics = false
DisablePProf = false
MetricsHttpAddress = ''
PProfHttpAddress = ''

[Rcmgr]
DisableRcmgr = false

[BlockSyncer]
Modules = ["epoch", "bucket", "object", "payment", "group", "permission","storage_provider"]
Dsn = "root:1q2w3e4r*@tcp(localhost:3306)/block_syncer?charset=utf8mb4&parseTime=True&loc=Local"
DsnSwitched = ""
RecreateTables = true
EnableDualDB = false
Workers = 10
